### ISSUE TITLE
"SQL Server Name Convention and T-SQL Programming Style" suggestions

### ISSUE THREAD

**Issue by IanKemp** [ktaranov/sqlserver-kit#173]
# SQL Server Object Name Convention

Nothing about unique indexes, do they fall under standard non-clustered?

# SQL Server Data Types Recommendation

"Exact Numerics", "bigint" - "what use" column seems incomplete

## General programming T-SQL style

> Avoid non-standard column aliases, use, if required, double-quotes for special characters and always AS keyword before alias:

I was under the impression that the recommended way to name aliases (and in fact anything) in T-SQL was to use square brackets, i.e.:

```sql
SELECT
       p.LastName AS [Last Name]
  FROM dbo.Person AS p;
```

# Stored procedures and functions programming style

Example sproc uses `create`...`alter` but since SQL 2016 you can use `create or alter`, consider either updating the example or adding a note.

#Dynamic T-SQL Recommendation

> Always use sp_executesql instead EXEC to prevent sql injection.

... except the sproc example given above does use `exec`.

**Comment by ktaranov** [comment]
Hi, Ian. Great thanks for your suggestions.

> Nothing about unique indexes, do they fall under standard non-clustered?

See this row in SQL Server Object Name Convention table (first table)
Table Unique (Alternative) Key | UQ | PascalCase | 128 | No | AK_ | No | Yes | [A-z][0-9] | AK_MyTable_MyColumn_AnotherColumn
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

> "Exact Numerics", "bigint" - "what use" column seems incomplete

Agree, I will fix it tomorrow

> I was under the impression that the recommended way to name aliases (and in fact anything) in T-SQL was to use square brackets, i.e.:

We use `"` because it ANSI standard and works in any relation database, you can modify this template for you needs.

> Example sproc uses create...alter but since SQL 2016 you can use create or alter, consider either updating the example or adding a note.

Agree, I will update it tomorrow.

> ... except the sproc example given above does use exec.

Could you provide more details about this suggestion?

**Comment by stephenjesus** [comment]
Hi guys, Try this free SQL Formatter online
[SQL Fomatter Online](https://onlinedevtools.in/online/sqlformatter)

**Comment by ktaranov** [comment]
Updated via https://github.com/ktaranov/sqlserver-kit/commit/ed1d9b6b84d92baf2a0cd6f0e010268e9185adb0
